In [1]:
import numpy as np
# יצירת מערך של 10 מספרים שלמים בטווח [1, 50]
arr1 = np.random.randint(1, 51, size=10)
print(f"המערך: {arr1}")

# חישוב הממוצע
mean_val = np.mean(arr1)
print(f"הממוצע של המספרים: {mean_val}")




המערך: [48 32 13 41 43 20 26 43 50 11]
הממוצע של המספרים: 32.7


In [2]:
# יצירת שני מערכים דו-ממדיים (מטריצות) בגודל 3x3 עם מספרים רנדומליים
matrix_a = np.random.randint(1, 11, size=(3, 3))
matrix_b = np.random.randint(1, 11, size=(3, 3))

# חיבור המערכים
matrix_sum = matrix_a + matrix_b

print("מערך א':\n", matrix_a)
print("מערך ב':\n", matrix_b)
print("תוצאת החיבור:\n", matrix_sum)

# בדיקת הממוצע של מערך התוצאה
total_mean = np.mean(matrix_sum)
print(f"\nהממוצע של תוצאת החיבור: {total_mean}")


מערך א':
 [[ 9  4  4]
 [ 7  1  5]
 [10  6  6]]
מערך ב':
 [[2 8 3]
 [7 7 5]
 [9 1 8]]
תוצאת החיבור:
 [[11 12  7]
 [14  8 10]
 [19  7 14]]

הממוצע של תוצאת החיבור: 11.333333333333334


In [3]:
# יצירת מערך של 20 מספרים
arr3 = np.random.randint(1, 101, size=20)
print(f"המערך המלא: {arr3}")

# מציאת המספרים הגדולים מ-50 באמצעות Boolean Indexing
greater_than_50 = arr3[arr3 > 50]
print(f"מספרים שגדולים מ-50: {greater_than_50}")

המערך המלא: [65 18 28 38 92 77 27 56 97 46  5 81 38 39 96 49 71 18 11 81]
מספרים שגדולים מ-50: [65 92 77 56 97 81 96 71 81]


In [4]:
# יצירת מערך עם מספרים מ-1 עד 10
arr4 = np.arange(1, 11)
print(f"המערך המקורי: {arr4}")

# ערבוב המערך (In-place)
np.random.shuffle(arr4)
print(f"המערך לאחר ערבוב: {arr4}")

# בחירת אלמנטים אקראיים מתוך המערך (למשל 3 אלמנטים)
random_selection = np.random.choice(arr4, size=3, replace=False)
print(f"בחירה אקראית של 3 אלמנטים: {random_selection}")

המערך המקורי: [ 1  2  3  4  5  6  7  8  9 10]
המערך לאחר ערבוב: [ 6  8 10  7  1  4  3  9  5  2]
בחירה אקראית של 3 אלמנטים: [10  5  3]
